// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import(
"github.com/gogf/gf/os/gtime"
)


// Prize is the golang structure for table prize.
type Prize struct {
    Id          int     `orm:"id,primary"   json:"id"`          //                                
    PrizeName   string  `orm:"prize_name"   json:"prizeName"`   //                                
    PrizeStock  int     `orm:"prize_stock"  json:"prizeStock"`  //                                
    PrizeImage  string  `orm:"prize_image"  json:"prizeImage"`  //                                
    Status      string  `orm:"status"       json:"status"`      // 1:激活，2: 未激活，3： 已删除  
    PrizeWeight float64 `orm:"prize_weight" json:"prizeWeight"` //                                
}


// ScoreDetail is the golang structure for table score_detail.
type ScoreDetail struct {
    Id           int         `orm:"id,primary"    json:"id"`           //   
    CreatedTime  *gtime.Time `orm:"created_time"  json:"createdTime"`  //   
    Prize        string      `orm:"prize"         json:"prize"`        //   
    UserId       int         `orm:"user_id"       json:"userId"`       //   
    ScoreHistory int         `orm:"score_history" json:"scoreHistory"` //   
}


// User is the golang structure for table user.
type User struct {
    Id       int    `orm:"id,primary" json:"id"`       //                                 
    Nickname string `orm:"nickname"   json:"nickname"` //                                 
    Remark   string `orm:"remark"     json:"remark"`   //                                 
    Status   string `orm:"status"     json:"status"`   // 1:未激活；2：已激活；3：已删除  
    Group    string `orm:"group"      json:"group"`    //                                 
}