// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"luckyarrow/app/dao/internal"
)

// prizeDao is the data access object for table prize.
// You can define custom methods on it to extend its functionality as you wish.
type prizeDao struct {
	*internal.PrizeDao
}

var (
	// Prize is globally public accessible object for table prize operations.
	Prize = prizeDao{
		internal.NewPrizeDao(),
	}
)

// Fill with you ideas below.