// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"luckyarrow/app/dao/internal"
)

// scoreDetailDao is the data access object for table score_detail.
// You can define custom methods on it to extend its functionality as you wish.
type scoreDetailDao struct {
	*internal.ScoreDetailDao
}

var (
	// ScoreDetail is globally public accessible object for table score_detail operations.
	ScoreDetail = scoreDetailDao{
		internal.NewScoreDetailDao(),
	}
)

// Fill with you ideas below.